version: "3"
services:
  api:
    image: ghcr.io/randomairborne/pastebot-api
    ports:
      - "8080:8080"
    networks:
      - proxy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.pbotapi.loadbalancer.server.port=8080"
        - "traefik.http.routers.pbotapi.rule=Host(`api.paste.valk.sh`)"
        - "traefik.http.routers.pbotapi.entrypoints=https"
        - "traefik.http.routers.pbotapi.tls.certresolver=letsencrypt"
  website:
    image: ghcr.io/randomairborne/pastebot-web
    ports:
      - "8080:8080"
    networks:
      - proxy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.pbotweb.loadbalancer.server.port=8080"
        - "traefik.http.routers.pbotweb.rule=Host(`paste.valk.sh`)"
        - "traefik.http.routers.pbotweb.entrypoints=https"
        - "traefik.http.routers.pbotweb.tls.certresolver=letsencrypt"
  bot:
    image: ghcr.io/randomairborne/pastebot
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - PASTEBIN_URL=${PASTEBIN_URL}
    deploy:
      labels:
        - "traefik.enable=false"
networks:
  proxy:
    external: true
