version: "3.7"
services:
  api:
    image: ghcr.io/randomairborne/pastebot-api
    ports:
      - "8080:8080"
    networks:
      - proxy
    deploy:
      labels:
        traefik:
          enable: "true"
          http:
            services.pbotapi.loadbalancer.server.port: 8080
            routers.pbotapi.rule: Host(`api.${PASTEBIN}`)
            routers.pbotapi.entrypoints: https
            routers.pbotapi.tls.certresolver: letsencrypt
            routers.pbotapi-insecure.rule: Host(`api.${PASTEBIN}`)
            routers.pbotapi-insecure.entrypoints: http
            routers.pbotapi-insecure.middlewares: https_redirect
            middlewares.pbotapi.redirectscheme.scheme: https
            middlewares.pbotapi.headers.accessControlAllowOriginList: https://${PASTEBIN},http://${PASTEBIN}
            middlewares.https_redirect.redirectscheme.scheme: https
            middlewares.https_redirect.redirectscheme.permanent: "true"
  website:
    image: ghcr.io/randomairborne/pastebot-web
    ports:
      - "8080:8080"
    networks:
      - proxy
    deploy:
      labels:
        traefik:
          enable: "true"
          http:
            services.pbotweb.loadbalancer.server.port: 8080
            routers.pbotweb.rule: Host(`${PASTEBIN}`)
            routers.pbotweb.entrypoints: https
            routers.pbotweb.tls.certresolver: letsencrypt
            routers.pbotweb-insecure.rule: Host(`${PASTEBIN}`)
            routers.pbotweb-insecure.entrypoints: http
            routers.pbotweb-insecure.middlewares: https_redirect
            middlewares.https_redirect.redirectscheme.scheme: https
            middlewares.https_redirect.redirectscheme.permanent: "true"
  bot:
    image: ghcr.io/randomairborne/pastebot
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      PASTEBIN: ${PASTEBIN}
    deploy:
      labels:
        traefik.enable: "false"
networks:
  proxy:
    external: true
