services:
  api:
    image: ghcr.io/randomairborne/pastebot-api
    ports:
      - "8080:8080"
  website:
    image: ghcr.io/randomairborne/pastebot-web
    ports:
      - "5000:8080"
  bot:
    image: ghcr.io/randomairborne/pastebot
    env_file:
      - .env
