version: "3"
services:
  api:
    image: ghcr.io/randomairborne/pastebot-api
    ports:
      - ":8080"
    networks:
      - default
      - ingress_default
    deploy:
      placement:
        constraints:
          - "node.role==manager"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pbotapi.rule=Host(`api.paste.valk.sh`)"
        - "traefik.http.routers.pbotapi.entrypoints=https"
        - "traefik.http.routers.pbotapi.tls.certresolver=letsencrypt"
        - "traefik.http.services.pbotapi.loadbalancer.server.port=8080"
  website:
    image: ghcr.io/randomairborne/pastebot-web
    ports:
      - ":8080"
    networks:
      - default
      - ingress_default
    deploy:
      placement:
        constraints:
          - "node.role==manager"
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.pbotweb.rule=Host(`paste.valk.sh`)"
        - "traefik.http.routers.pbotweb.entrypoints=https"
        - "traefik.http.routers.pbotweb.tls.certresolver=letsencrypt"
        - "traefik.http.services.pbotweb.loadbalancer.server.port=8080"
  bot:
    image: ghcr.io/randomairborne/pastebot
    env_file:
      - .env
networks:
  ingress_default:
    external: true
