version: "3.7"
services:
  web:
    image: ghcr.io/randomairborne/pastebot-web
    ports:
      - ":8080"
    networks:
      - proxy
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.services.pbotweb.loadbalancer.server.port: 8080
        traefik.http.routers.pbotweb.rule: Host(`${PASTEBIN}`)
        traefik.http.routers.pbotweb.entrypoints: https
        traefik.http.routers.pbotweb.tls.certresolver: letsencrypt
        traefik.http.routers.pbotweb-insecure.rule: Host(`${PASTEBIN}`)
        traefik.http.routers.pbotweb-insecure.entrypoints: http
        traefik.http.middlewares.https-redirect.redirectscheme.scheme: https
        traefik.http.middlewares.https-redirect.redirectscheme.permanent: "true"
        traefik.http.middlewares.pbotweb-mw.headers.accesscontrolalloworiginlist: https://${PASTEBIN}
        traefik.http.routers.pbotweb-insecure.middlewares: https_redirect
        traefik.http.routers.pbotweb.middlewares: pbotweb-mw

  bot:
    image: ghcr.io/randomairborne/pastebot
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      PASTEBIN: ${PASTEBIN}
    deploy:
      labels:
        traefik.enable: "false"
networks:
  proxy:
    external: true
